config/routes.rb
Rails.application.routes.draw do
  root to: 'visitors#index'
  resources :searches, only: [:index, :create]
  resources :stores, only: [:show]
  get '/auth/:provider/callback', to: 'sessions#create'
  get 'session/:action', to: 'sessions'
end

app/models/insta_id.rb
class InstaId

  def self.user_id(username: )
    current_user = Instagram.user_search(username, count:1)[0]
    current_user.id
  end
end

app/models/insta_parser.rb
class InstaParser

  def initialize(user_info:, media_info:)
    @user_info = user_info
    @media_info = media_info
  end

  def parse_store
    #store = current_user.to_hash.symbolize_keys.except(:full_name)
    store = @user_info.symbolize_keys.except(:full_name)
    store[:insta_id] = store.delete :id
    store
  end

  def parse_media
    @media_info.inject([]) do |media, medium|
      media << parse_images(medium).merge(parse_caption(medium))
    end
  end

  private

  def parse_caption(medium)
    caption = {}
    if medium.caption
      caption[:caption_text] = medium.caption.text
      caption.merge!(parse_tag(caption[:caption_text]))
    end
    caption
  end

  def parse_tag(caption)
    { price: caption.scan(/\$\d+\.*\d*/)[0].to_s.gsub!(/\$/, ''), category: caption.scan(/##\S*/)[0].to_s.encode('utf-8', 'utf-8').scan(/[[:alnum:]]+/)[0], name: caption.scan(/\!#\S*/)[0].to_s.encode('utf-8', 'utf-8').scan(/[[:alnum:]]+/)[0] }
  end

  def parse_images(medium)
    data = medium.to_hash.slice("images")["images"].deep_symbolize_keys
    data.transform_values { |x| x[:url] }
  end

end

app/models/insta_save.rb
class InstaSave
  def self.store(store_info)
    store = Store.new do |s|
      s.username = store_info[:username]
      s.insta_id = store_info[:id]
      s.profile_picture = store_info[:profile_picture]
    end

    store
  end

  def self.media_and_tag(media_info, store)
    media_info.inject([]) do |media, medium|
      new_medium(medium, store)
    end

  end

  private

  def self.new_medium(medium_info, store)
    medium = Medium.create do |m|
      m.store_id = store.id
      m.caption_text = medium_info[:caption_text]
      m.low_resolution = medium_info[:low_resolution]
      m.thumbnail = medium_info[:thumbnail]
      m.standard_resolution = medium_info[:standard_resolution]
    end
    new_tag(medium_info, medium)
  end

  def self.new_tag(caption_info, medium)
    tag = Tag.create do |t|
      t.medium_id = medium.id
      t.price = caption_info[:price]
      t.category = caption_info[:category]
      t.name = caption_info[:name]
    end

    tag
  end
end

app/models/insta_worker.rb
class InstaWorker
  def initialize(user_info:, media_info:)
    @user_info = user_info
    @media_info = media_info
  end

  def save
    parse

    store = InstaSave.store(@user_info)

    if store.save
      @store_id = store.id

      InstaSave.media_and_tag(@parse_media_info, store)
    else
      false
    end
  end

  def store_id
    @store_id
  end

  private

  def parse
    data = InstaParser.new(user_info: @user_info, media_info: @media_info)
    @parse_media_info = data.parse_media
  end

end

app/models/medium.rb
class Medium < ActiveRecord::Base
  belongs_to :store
  has_one :tag
end

app/models/store.rb
class Store < ActiveRecord::Base
  has_many :media
  validates :username, uniqueness: true
end

app/models/tag.rb
class Tag < ActiveRecord::Base
  belongs_to :medium
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def index
    @store = Store.all
  end

  def create
    worker = InstaWorker.new(user_id: user_id)
    if worker.save
      redirect_to store_path(worker.store_id)
    else
      redirect_to store_path(Store.find_by(username: params[:search]))
    end

  end

  private

  def user_id
    InstaId.user_id(username: params[:search])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
#  def create
#    session[:access_token] = request.env['omniauth.auth'].credentials.token
#    worker = InstaWorker.new(user_info: request.env['omniauth.auth'])
#    if worker.save
#      redirect_to store_path(worker.store_id)
#    else
#      redirect_to store_path(Store.find_by(username: params[:search]))
#    end
#  end

  def connect
    puts "trying to connect to instagram"
    redirect_to Instagram.authorize_url(redirect_uri: CALLBACK_URL)
  end

  def disconnect
    # logout
    session[:access_token] = nil
    redirect_to root_path
  end

  def callback
    # if the user denied authorization
    if params[:error]
      # do something
      redirect_to root_path
    else
      # get response
      response = Instagram.get_access_token(params[:code], redirect_uri: CALLBACK_URL)
      user_info = response.user
      session[:access_token] = response.access_token
      media_info = Instagram.client(access_token: session[:access_token]).user_recent_media
      # create store
      worker = InstaWorker.new(user_info: user_info, media_info: media_info)

      if worker.save
        redirect_to store_path(worker.store_id)
      else
        redirect_to store_path(Store.find_by(insta_id: user_info.id))
      end
    end
  end
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController
  def show
    @media = Store.find(params[:id]).media
  end
end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
  def index
    @store = Store.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><%= link_to 'Home', root_path %></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li><%= link_to 'About', page_path('about') %></li>
<% if session[:access_token] %>
  <li><%= link_to 'Already Login, go Log Out', '/session/disconnect' %><li>
<% else %>
  <li><%= link_to 'Instagram', '/session/connect' %></li>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Fourm Mvp" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Fourm Mvp" %>">
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%# Modernizr is required for Zurb Foundation %>
    <%= javascript_include_tag 'vendor/modernizr' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>About the Website</h3>
<p>
This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/searches/index.html.erb
<h1>menu</h1>

<% @store.each do |store| %>
  <h1> * <%= store.username %></h1> <br>
<% end %>

app/views/stores/show.html.erb
<% @media.each do |medium| %>
  <div class='box'>
    <div class='content'>
      <%= image_tag medium.standard_resolution %>
    </div>
    <div class='info'>
      <span class='price'> $<%= medium.tag.price %>
      <span class='name'> <%= medium.tag.name %>
    </div>
  </div>
<% end %>

app/views/visitors/index.html.erb
<h3>FourM-mvp</h3>

<%= form_tag searches_path, method: "post" do %>
  <%= label_tag(:search, "Search for:") %>
  <%= text_field_tag :search, params[:search], :placeholder => "Search for username" %>
  <%= submit_tag("Search") %>
<% end %>

<% @store.each do |store| %>
  <h1> * <%= link_to store.username, store %></h1> <br>
<% end %>